---
abstract: 'Dochazka ATT system shared modules'
author:
  - 'Smithfarm <presnypreklad@gmail.com>'
build_requires:
  Params::Validate: '1.06'
  Test::Fatal: '0'
configure_requires:
  Module::Build: '0.37'
  Software::License: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.141170'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dochazka
provides:
  App::Dochazka:
    file: lib/App/Dochazka.pm
    version: '0.157'
  App::Dochazka::Model::Activity:
    file: lib/App/Dochazka/Model/Activity.pm
    version: '0.157'
  App::Dochazka::Model::Employee:
    file: lib/App/Dochazka/Model/Employee.pm
    version: '0.157'
  App::Dochazka::Model::Interval:
    file: lib/App/Dochazka/Model/Interval.pm
    version: '0.157'
  App::Dochazka::Model::Lock:
    file: lib/App/Dochazka/Model/Lock.pm
    version: '0.157'
  App::Dochazka::Model::Privhistory:
    file: lib/App/Dochazka/Model/Privhistory.pm
    version: '0.157'
  App::Dochazka::Model::Schedhistory:
    file: lib/App/Dochazka/Model/Schedhistory.pm
    version: '0.157'
  App::Dochazka::Model::Schedintvls:
    file: lib/App/Dochazka/Model/Schedintvls.pm
    version: '0.157'
  App::Dochazka::Model::Schedule:
    file: lib/App/Dochazka/Model/Schedule.pm
    version: '0.157'
  App::Dochazka::Model::Session:
    file: lib/App/Dochazka/Model/Session.pm
    version: '0.157'
  App::Dochazka::Model::Shared:
    file: lib/App/Dochazka/Model/Shared.pm
    version: '0.157'
requires:
  Params::Validate: '1.06'
  perl: '5.012'
resources:
  homepage: https://sourceforge.net/projects/dochazka/
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: https://sourceforge.net/p/dochazka/code/
version: '0.157'
